services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  spring-boot-url-shortner:
    image: ananyadixit252/spring-boot-url-shortner
    container_name: spring-boot-url-shortner
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres